/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew.clothing.store;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author manjeet
 */
public class billing_section extends javax.swing.JFrame {

    /**
     * Creates new form billing_section
     */
    public billing_section() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Buy = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Remove = new javax.swing.JButton();
        GenerateBill = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setBackground(new java.awt.Color(0, 102, 0));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Type", "Brand Name", "Item Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(15, 60, 800, 440);

        jLabel2.setFont(new java.awt.Font("Raavi", 0, 18)); // NOI18N
        jLabel2.setText("Total Amount To Be Paid:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(830, 60, 200, 33);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(860, 100, 180, 30);

        jLabel3.setFont(new java.awt.Font("Raavi", 0, 14)); // NOI18N
        jLabel3.setText("Rs.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(830, 110, 30, 20);

        Buy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Buy.setText("Buy");
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });
        getContentPane().add(Buy);
        Buy.setBounds(850, 350, 160, 23);

        Cancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(850, 420, 160, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Remove This Item :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(830, 140, 120, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Item Code :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(830, 190, 70, 15);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(920, 180, 100, 30);

        Remove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove);
        Remove.setBounds(870, 230, 100, 23);

        GenerateBill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GenerateBill.setText("Generate Bill");
        GenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateBill);
        GenerateBill.setBounds(840, 290, 180, 23);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1060, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBillActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/vogue", "root", "kvuc");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from bill_items;");
        int ic, p;
        String b,i,t;
        while(rs.next()){
        ic = rs.getInt("Item_code");
        p = rs.getInt("price");
        b = rs.getString("brandname");
        i = rs.getString("Item_name");
        t = rs.getString("type");
        Object r[] = {ic,t,b,i,p};
        tm.addRow(r);
        }
           rs.close();
           stmt.close();
           con.close();
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e.getMessage());}
        
        /* */
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/vogue", "root", "kvuc");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select sum(price)from bill_items;");
        int b=0;
        while(rs.next()){ b = rs.getInt("sum(price)");}
        jTextField1.setText(""+ b);
           rs.close();
           stmt.close();
           con.close();
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e.getMessage());}
    }//GEN-LAST:event_GenerateBillActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        
        tm.setRowCount(0);
        /*   */
        
        int a = Integer.parseInt(jTextField2.getText());
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/vogue", "root", "kvuc");
        Statement stmt = con.createStatement();
        int d = stmt.executeUpdate("delete from bill_items where item_code="+ a +";");
        
           
           stmt.close();
           con.close();
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e.getMessage());}
        /*   */
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/vogue", "root", "kvuc");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select * from bill_items;");
        int ic, p;
        String b,i,t;
        while(rs.next()){
        ic = rs.getInt("Item_code");
        p = rs.getInt("price");
        b = rs.getString("brandname");
        i = rs.getString("Item_name");
        t = rs.getString("type");
        Object r[] = {ic,t,b,i,p};
        tm.addRow(r);
        }
           rs.close();
           stmt.close();
           con.close();
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e.getMessage());}
        
        /*   */
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/vogue", "root", "kvuc");
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery("select sum(price)from bill_items;");
        int b=0;
        while(rs.next()){ b = rs.getInt("sum(price)");}
        jTextField1.setText(""+ b);
           rs.close();
           stmt.close();
           con.close();
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e.getMessage());}
    }//GEN-LAST:event_RemoveActionPerformed

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
        // TODO add your handling code here:
       DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
         JOptionPane.showMessageDialog(null,"Thank You For Shopping With VOGUE.\n \n *Items Will Reach At The GIven Address In A Week.");
        this.dispose();
        /*  */
        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con= DriverManager.getConnection("jdbc:mysql://localhost/vogue", "root", "kvuc");
        Statement stmt = con.createStatement();
        int m = stmt.executeUpdate("delete from bill_items;");
        
           
           stmt.close();
           con.close();
        }
        catch(Exception e){ JOptionPane.showMessageDialog(null, e.getMessage());}
        
    }//GEN-LAST:event_BuyActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing_section().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buy;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton GenerateBill;
    private javax.swing.JButton Remove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
