/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgnew.clothing.store;

/**
 *
 * @author manjeet
 */
public class Men extends javax.swing.JFrame {

    /**
     * Creates new form Men
     */
    public Men() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Accessories = new javax.swing.JButton();
        TopWear = new javax.swing.JButton();
        Shoes = new javax.swing.JButton();
        BottomWear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/clothing/store/anf-division-mens-springjeans-20121221.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 100, 380, 220);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/clothing/store/MSW_3_7x6.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 100, 315, 225);

        Accessories.setBackground(new java.awt.Color(0, 0, 51));
        Accessories.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Accessories.setForeground(new java.awt.Color(255, 255, 255));
        Accessories.setText("ACCESSORIES");
        Accessories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Accessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccessoriesActionPerformed(evt);
            }
        });
        getContentPane().add(Accessories);
        Accessories.setBounds(780, 0, 220, 70);

        TopWear.setBackground(new java.awt.Color(0, 0, 51));
        TopWear.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        TopWear.setForeground(new java.awt.Color(255, 255, 255));
        TopWear.setText("TOP  WEAR");
        TopWear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TopWear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopWearActionPerformed(evt);
            }
        });
        getContentPane().add(TopWear);
        TopWear.setBounds(20, 0, 250, 70);

        Shoes.setBackground(new java.awt.Color(0, 0, 51));
        Shoes.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Shoes.setForeground(new java.awt.Color(255, 255, 255));
        Shoes.setText("SHOES");
        Shoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Shoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShoesActionPerformed(evt);
            }
        });
        getContentPane().add(Shoes);
        Shoes.setBounds(550, 0, 210, 70);

        BottomWear.setBackground(new java.awt.Color(0, 0, 51));
        BottomWear.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        BottomWear.setForeground(new java.awt.Color(255, 255, 255));
        BottomWear.setText("BOTTOM   WEAR");
        BottomWear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BottomWear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottomWearActionPerformed(evt);
            }
        });
        getContentPane().add(BottomWear);
        BottomWear.setBounds(300, 0, 240, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/clothing/store/Diesel-Men-Clothing-photos-2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 360, 340, 230);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/clothing/store/Gucci-suit.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(740, 330, 250, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/clothing/store/mensPromoTile.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 340, 360, 250);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgnew/clothing/store/2011720325855761 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 110, 231, 170);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\documents  c\\NetBeansProjects\\New Clothing Store\\src\\pkgnew\\clothing\\store\\abstract_black_blue_Wallpaper_1680x1050_wallpaperhere.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1020, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TopWearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TopWearActionPerformed
        // TODO add your handling code here:
        Top_Wear_M a;
        a = new Top_Wear_M();
        a.setVisible(true);
    }//GEN-LAST:event_TopWearActionPerformed

    private void BottomWearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottomWearActionPerformed
        // TODO add your handling code here:
        jeans_m a;
        a = new jeans_m();
        a.setVisible(true);
        
    }//GEN-LAST:event_BottomWearActionPerformed

    private void ShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShoesActionPerformed
        // TODO add your handling code here:
        shoes_men a;
        a = new shoes_men();
        a.setVisible(true);
    }//GEN-LAST:event_ShoesActionPerformed

    private void AccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccessoriesActionPerformed
        // TODO add your handling code here:
        accessories_m a;
        a = new accessories_m();
        a.setVisible(true);
    }//GEN-LAST:event_AccessoriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Men.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Men().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accessories;
    private javax.swing.JButton BottomWear;
    private javax.swing.JButton Shoes;
    private javax.swing.JButton TopWear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
